apiVersion: v1
name: cert-manager-webhook-duckdns
version: v1.3.0
appVersion: v1.3.0
description: A Helm chart for cert manager (v1.17.2) webhook solver for ACME DNS01 challenge via DuckDNS
home: https://github.com/dperez9/cert-manager-webhook-duckdns
icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
keywords:
  - cert-manager
  - webhook
  - letsencrypt
  - tls
sources:
  - https://github.com/ebrianne/cert-manager-webhook-duckdns
maintainers:
  - name: Daniel Perez
    email: danielpero98@gmail.com
    url: ""